### ISSUE TITLE
Ability to submit metrics through datadog-agent instead of datadog API

### ISSUE THREAD

**Issue by fotinakis** [mozmeao/cloudflare-datadog#11]
Hello! Thanks for writing this, it's been super helpful.

Would love the ability to push metrics to a locally running datadog-agent instead of directly to the API. In kubernetes world where this bridge is running next to an already-running datadog-agent, this would have a nice side-effect of re-using that agent's hostname rather than consuming a datadog host for just this application.

**Comment by Overbryd** [comment]
Hi,

have the same idea/problem here.

Do you have a reference to documentation on that?

Because as I see the datadog agent can only receive metrics in the form of udp packets, and this protocol does not allow to set the timestamp the event occurred.

Best would maybe be to actually implement a datadog agent check that regularly pulls metrics and pushes them from within the agent.

**Comment by jgmize** [comment]
This might be possible as an integration: https://docs.datadoghq.com/developers/integrations/

**Comment by glogiotatidis** [comment]
Thanks for reaching out @fotinakis, @Overbryd. I somehow lost the original ping on this one.

> Because as I see the datadog agent can only receive metrics in the form of udp packets, and this protocol does not allow to set the timestamp the event occurred.

While I very much like using the datadog agent and I see the benefits of sending stats to a local agent, as @Overbryd suggests the `statsd` interface datadog-agent implements does not allow for timestamps. 

A custom integration suggested by @jgmize could be a way fwd with this but that's something we will not implement atm b/c the current setup works for us. 

We always welcome pull requests!

**Comment by glogiotatidis** [comment]
I think it's fair to close this one due to lack of activity. Always feel free to re-open with new info and submit PRs. Thanks!
