### ISSUE TITLE
Update to use cloudflare-python

### ISSUE THREAD

**Issue by jgmize** [mozmeao/cloudflare-datadog#5]
See https://github.com/mozmar/cloudflare-datadog/pull/3#issuecomment-285912404

**Comment by glogiotatidis** [comment]
We're using cloudflare api v4 already. I guess you meant 'Update to use Cloudflare-python'

**Comment by jgmize** [comment]
Good catch @glogiotatidis, thanks

**Comment by jgmize** [comment]
fixed in #7
